language: cpp
os:
  - linux
  - osx
compiler: 
  - gcc
  - clang
cache:
  apt: true
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-4.7
      - gcc-4.7
      - libboost-all-dev
notifications:
  email: false
script: 
  - cmake .; make; bin/mcmc -e example_edge_list.txt -P 0.6 0.1 0.1 0.6 -n 20 20 -r -t 1000 --maximize -c exponential;
  - cmake .; make; bin/mcmc_history -e example_edge_list.txt -P 0.6 0.1 0.1 0.6 -n 20 20 -r -t 100 -f 40 -b 50 -s; 
